kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: tt-ibm-ace-mqc-soe-ms2-build
  namespace: ace
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ace11002mqc91ms2
        from:
          kind: ImageStreamTag
          namespace: ace
          name: 'ace11002mqc91ms2:latest'
  replicas: 1
  selector:
    app: tt-ibm-ace-mqc-soe-ms2-build
    deploymentconfig: ibm-ace-mqc-soe-ms2-build
  template:
    metadata:
      labels:
        app: tt-ibm-ace-mqc-soe-ms2-build
        deploymentconfig: ibm-ace-mqc-soe-ms2-build
    spec:
      containers:
        - name: ace11002mqc91ms2
          image: >-
            __IMAGE__
          ports:
            - containerPort: 7600
              protocol: TCP
            - containerPort: 7800
              protocol: TCP
          env:
            - name: LICENSE
              value: accept
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
